force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>object to hold job applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>related account; associated company for the job application</description>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>detailed information about the job, such as responsibilities, qualifications, benefits, etc</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>the job location</description>
    <label>Location</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>personal notes about the job application</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Title__c</fullName>
    <description>the specific job title or position being applied for</description>
    <label>Position/Title</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>the expected salary for the job position</description>
    <label>Salary</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the current status of the job application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>web link of the job posting</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/JoobleSaveToSalesforce_Test.cls
/**
 * Apex Class: JoobleSaveToSalesforce_Test
 * Description: This class is used to test the JoobleSaveToSalesforce class, validating the Account and Job_Application__c records
 * created from the JSON string returned from the joobleJobSearch lwc
 * Created Date: 2024-06-16
 * Last Modified: 
 */

@isTest
public with sharing class JoobleSaveToSalesforce_Test {
    
    @isTest
    static void testSaveToSalesforce_Positive(){

        Account testAccount = new Account(Name = 'Cloud Consulting');
        insert testAccount;

        String payload = '[{"company":"Data Dream","id":1988165115712216800,"link":"https://jooble.org","location":"Austin, TX","salary":"80000","snippet":"Tableau Admin, Locals Preferred","source":"appcast.io","title":"Tableau Admin","type":"","updated":"2024-06-13T00:00:00.0000000"},{"company":"Cloud Consulting","id":6975534765270566000,"link":"https://jooble.org","location":"Austin, TX","salary":"","snippet":"Salesforce Admin, you will be responsible for the administration, configuration, and ongoing maintenance of our Salesforce instance... ","source":"appcast.io","title":"Salesforce Admin","type":"Contractor","updated":"2024-06-15T00:00:00.0000000"}]';

        Test.startTest();
            JoobleSaveToSalesforce.saveToSalesforce(payload);
        Test.stopTest();

       
        List<Account> accountsCreated = [
            SELECT Id, Name FROM Account WHERE Id != :testAccount.Id
        ];

        Assert.areEqual(1, accountsCreated.size(), 'Expected only one account to be created');
        Assert.areEqual('Data Dream', accountsCreated[0].Name, 'Name of account does not match expected value');

        List<Job_Application__c> jobAppsCreated = [
            SELECT Id, Name, Position_Title__c, Location__c, Salary__c, Description__c, URL__c, Notes__c, Status__c, Company_Name__c
            FROM Job_Application__c
        ];

        Assert.areEqual(2, jobAppsCreated.size(), 'Expected two job application records to be created');
        
        for(Job_Application__c jobApp : jobAppsCreated){
            if(jobApp.Position_Title__c == 'Tableau Admin'){
                Assert.areEqual('Austin, TX', jobApp.Location__c, 'Location does not match expected value on Job Application');
                Assert.areEqual(80000, jobApp.Salary__c, 'Salary does not match expected value on Job Application');
                Assert.areEqual('Tableau Admin, Locals Preferred', jobApp.Description__c, 'Description does not match expected value on Job Application');
                Assert.areEqual('https://jooble.org', jobApp.URL__c, 'URL does not match expected value on Job Application');
                Assert.areEqual('Saved', jobApp.Status__c, 'Status does not match expected value on Job Application');
                Assert.areEqual(accountsCreated[0].Id, jobApp.Company_Name__c, 'Company Name does not match expected value on Job Application');
                Assert.areEqual('Source: appcast.io', jobApp.Notes__c, 'Notes do not match expected value on Job Application');
            }
        }

    }

    @isTest
    static void testSaveToSalesforce_Negative(){

        Account testAccount = new Account(Name = 'Cloud Consulting');
        insert testAccount;

        String payload = '';

        Test.startTest();
            JoobleSaveToSalesforce.saveToSalesforce(payload);
        Test.stopTest();

        List<Account> accountsCreated = [
            SELECT Id, Name FROM Account WHERE Id != :testAccount.Id
        ];

        Assert.areEqual(0, accountsCreated.size(), 'Expected no account records found');

        List<Job_Application__c> jobAppsCreated = [
            SELECT Id, Name, Position_Title__c, Location__c, Salary__c, Description__c, URL__c, Notes__c, Status__c, Company_Name__c
            FROM Job_Application__c
        ];

        Assert.areEqual(0, jobAppsCreated.size(), 'Expected no job application records found');

    }

}