force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>object to hold job applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>related account; associated company for the job application</description>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>detailed information about the job, such as responsibilities, qualifications, benefits, etc</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>the job location</description>
    <label>Location</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>personal notes about the job application</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Title__c</fullName>
    <description>the specific job title or position being applied for</description>
    <label>Position/Title</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>the expected salary for the job position</description>
    <label>Salary</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the current status of the job application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>web link of the job posting</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/JoobleSaveToSalesforce.cls
public with sharing class JoobleSaveToSalesforce {

    @AuraEnabled(cacheable=false)
    public static void saveToSalesforce(String payload) {

        try {

            System.debug('*** INSIDE SAVE TO SALESFORCE');
            System.debug('*** Retrieved rows: ' + payload);

            List<Object> jobRecords = (List<Object>) JSON.deserializeUntyped(payload);
            System.debug('*** jobMAP' + jobRecords);

            // Parse JSON Data to create a map of Job Applications and Company Names
            Map<String, Job_Application__c> mapJoobleIdToJobApplication = new Map<String, Job_Application__c>();
            Map<String, String> mapJoobleIdToCompanyName = new Map<String, String>();
    
            for(Object record : jobRecords) {
                Map<String, Object> dataObject = (Map<String,Object>) record;

                Job_Application__c job = new Job_Application__c();
                Long joobleId = (Long) dataObject.get('id');
                String joobleIdString = String.valueOf(joobleId);
                String companyName = (String) dataObject.get('company');
                job.Name = (String) dataObject.get('title');
                job.Location__c = (String) dataObject.get('location');
                job.Position_Title__c = (String) dataObject.get('title');
                String salaryString = (String) dataObject.get('salary');
                job.Salary__c = String.isEmpty(salaryString) ? 0 : Decimal.valueOf(salaryString);
                job.Description__c = (String) dataObject.get('snippet');
                job.URL__c = (String) dataObject.get('link');
                job.Notes__c = (String) dataObject.get('source');
                job.Status__c = 'Saved';
    
                mapJoobleIdToJobApplication.put(joobleIdString, job);
                mapJoobleIdToCompanyName.put(joobleIdString, companyName);
            }


            System.debug('*** mapJoobleIdToJobApplication: '+ mapJoobleIdToJobApplication);
            System.debug('*** mapJoobleIdToCompanyName: '+ mapJoobleIdToCompanyName);

            // Process Company Names and insert to Salesforce if needed
            Set<String> companyNames = new Set<String>(mapJoobleIdToCompanyName.values());  

            System.debug('*** companyNames: '+ companyNames);
             
            // Get existing accounts in Salesforce that match company names
            List<Account> existingAccounts = [ 
                SELECT Id, Name
                FROM Account
                WHERE Name IN :companyNames
            ];

            System.debug('*** existingAccounts: '+ existingAccounts);

            // Create Map of Account Name : Account
            Map<String, Account> mapAccountNameToAccount = new Map<String, Account>();

            for(Account a : existingAccounts) {
                mapAccountNameToAccount.put(a.Name, a);
            }

            // Create Account record for Accounts that do not already exist in Salesforce
            List<Account> accountsToInsert = new List<Account>(); 

            for (String companyName : companyNames){
                if (!mapAccountNameToAccount.containsKey(companyName)) {
                    Account newAccount = new Account(Name = companyName);
                    accountsToInsert.add(newAccount);
                    mapAccountNameToAccount.put(companyName, newAccount);
                }
            }
            // Insert Account records
            if(!accountsToInsert.isEmpty()){
                insert accountsToInsert;
            }

            System.debug('*** accounts to insert: '+ accountsToInsert);
            System.debug('*** accounts map name to account AFTER INSERT OPERATION: '+ mapAccountNameToAccount);


            // Create Map of JoobleId : Accounts 
            Map<String, Account> mapJoobleIdToAccount = new Map<String, Account>();
            for (String joobleIdString : mapJoobleIdToCompanyName.keySet()) {
                mapJoobleIdToAccount.put(joobleIdString, mapAccountNameToAccount.get(mapJoobleIdToCompanyName.get(joobleIdString)));
            }

            // Update Map of Jooble Id : Applications with Account Id from mapJoobleIdToAccount
            for(String joobleIdString : mapJoobleIdToJobApplication.keySet()) {
                mapJoobleIdToJobApplication.get(joobleIdString).Company_Name__c = mapJoobleIdToAccount.get(joobleIdString).Id;
            }

            insert mapJoobleIdToJobApplication.values();

            System.debug('*** mapJoobleIdToJobApplication AFTER INSERT OPERATION: '+ mapJoobleIdToJobApplication);

            } catch (Exception e) {
            System.debug('Error in saveToSalesforce: ' + e.getMessage());
            System.debug('Stack trace: ' + e.getStackTraceString());
            
        }
       
    }

}