force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Class Name that generated Exception</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <description>Exception Error Message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <description>type of Exception</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <description>line number that generated the Exception</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <description>Method Name that generated the Exception</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Exception Stack Trace</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ErrorLogUtility.cls
/**
 * Apex Class: ErrorLogUtility
 * Description: This class handles any exceptions, creating an ErrorLog__c record that is saved to Salesforce
 * Created Date: 2024-06-25
 * Last Modified: 2024-07-01
 */

public with sharing class ErrorLogUtility {
    
    
    public static void logError(Exception e){

        ErrorLog__c errorLog = createErrorLog(e);
        insert as System errorLog;

    }


    private static ErrorLog__c createErrorLog(Exception e){

        ErrorLog__c errorLog = new ErrorLog__c();
        errorLog.ExceptionMessage__c = e.getMessage();
        errorLog.ExceptionType__c = e.getTypeName();
        errorLog.LineNumber__c = e.getLineNumber();
        String stackTrace = e.getStackTraceString();
        errorLog.StackTrace__c = stackTrace;
        errorLog.ClassName__c = stackTrace.substringAfter('.').substringBefore('.'); 
        errorLog.MethodName__c = stackTrace.substringBefore(':').substringAfter(errorLog.ClassName__c).substringAfter('.');

        return errorLog;

    }
}